SELECT 
    COUNT(ED.ID) AS COUNT
FROM ECOLI_DATA AS ED
WHERE
    CONVERT(CONV(ED.GENOTYPE, 10, 2), CHAR) NOT LIKE "%1_"
    AND (CONVERT(CONV(ED.GENOTYPE, 10, 2), CHAR) LIKE "%1"
    OR CONVERT(CONV(ED.GENOTYPE, 10, 2), CHAR) LIKE "%1__")
;